const shows = [
  {id:"severance",title:"Severance",year:2022,network:"Apple TV+",genres:["Sci-Fi","Mystery"],score:4.5,art:"linear-gradient(145deg,#c2ded3 0%,#819f91 34%,#3d554b 68%,#1b2924)",description:"Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. A colleague's arrival sets them on a search for the truth behind their jobs.",seasons:[[{name:"Good News About Hell",air:"Feb 18, 2022",runtime:"57m"},{name:"Half Loop",air:"Feb 18, 2022",runtime:"46m"},{name:"In Perpetuity",air:"Feb 25, 2022",runtime:"51m"},{name:"The You You Are",air:"Mar 4, 2022",runtime:"47m"},{name:"The Grim Barbarity of Optics and Design",air:"Mar 11, 2022",runtime:"45m"},{name:"Hide and Seek",air:"Mar 18, 2022",runtime:"42m"},{name:"Defiant Jazz",air:"Mar 25, 2022",runtime:"40m"},{name:"What's for Dinner?",air:"Apr 1, 2022",runtime:"40m"},{name:"The We We Are",air:"Apr 8, 2022",runtime:"40m"}],[{name:"Hello, Ms. Cobel",air:"Jan 17, 2025",runtime:"43m"},{name:"Goodbye, Mrs. Selvig",air:"Jan 24, 2025",runtime:"46m"},{name:"Who Is Alive?",air:"Jan 31, 2025",runtime:"49m"},{name:"Woe's Hollow",air:"Feb 7, 2025",runtime:"48m"},{name:"Trojan's Horse",air:"Feb 14, 2025",runtime:"42m"},{name:"Attila",air:"Feb 21, 2025",runtime:"43m"},{name:"Chikhai Bardo",air:"Feb 28, 2025",runtime:"50m"},{name:"Sweet Vitriol",air:"Mar 7, 2025",runtime:"43m"},{name:"The After Hours",air:"Mar 14, 2025",runtime:"49m"},{name:"Cold Harbor",air:"Mar 21, 2025",runtime:"51m"}]]},
  {id:"succession",title:"Succession",year:2018,network:"HBO",genres:["Drama","Comedy"],score:4.6,art:"linear-gradient(145deg,#c4ad83 0%,#77745b 35%,#444842 68%,#1c2423)",description:"The Roy family is known for controlling the biggest media and entertainment company in the world. But when their aging father begins to step back, the future of the company becomes a battle among his children.",seasons:[[{name:"Celebration",air:"Jun 3, 2018",runtime:"60m"},{name:"Shit Show at the Fuck Factory",air:"Jun 10, 2018",runtime:"59m"},{name:"Lifeboats",air:"Jun 17, 2018",runtime:"58m"},{name:"Sad Sack Wasp Trap",air:"Jun 24, 2018",runtime:"58m"},{name:"I Went to Market",air:"Jul 1, 2018",runtime:"59m"},{name:"Which Side Are You On?",air:"Jul 8, 2018",runtime:"58m"},{name:"Austerlitz",air:"Jul 15, 2018",runtime:"59m"},{name:"Prague",air:"Jul 22, 2018",runtime:"58m"},{name:"Pre-Nuptial",air:"Jul 29, 2018",runtime:"57m"},{name:"Nobody Is Ever Missing",air:"Aug 5, 2018",runtime:"62m"}],[{name:"The Summer Palace",air:"Aug 11, 2019",runtime:"64m"},{name:"Vaulter",air:"Aug 18, 2019",runtime:"57m"},{name:"Hunting",air:"Aug 25, 2019",runtime:"58m"},{name:"Safe Room",air:"Sep 1, 2019",runtime:"57m"},{name:"Tern Haven",air:"Sep 8, 2019",runtime:"59m"}]]},
  {id:"the-bear",title:"The Bear",year:2022,network:"FX",genres:["Comedy","Drama"],score:4.3,art:"linear-gradient(145deg,#e5a963 0%,#b36642 38%,#693d31 70%,#291f1a)",description:"A young chef from the fine dining world returns to Chicago to run his family's sandwich shop. He and his staff work together to transform the restaurant while navigating grief and the pressure of the kitchen.",seasons:[[{name:"System",air:"Jun 23, 2022",runtime:"27m"},{name:"Hands",air:"Jun 23, 2022",runtime:"29m"},{name:"Brigade",air:"Jun 23, 2022",runtime:"28m"},{name:"Dogs",air:"Jun 23, 2022",runtime:"26m"},{name:"Sheridan",air:"Jun 23, 2022",runtime:"27m"},{name:"Ceres",air:"Jun 23, 2022",runtime:"29m"},{name:"Review",air:"Jun 23, 2022",runtime:"20m"},{name:"Braciole",air:"Jun 23, 2022",runtime:"29m"}],[{name:"Beef",air:"Jun 22, 2023",runtime:"30m"},{name:"Pasta",air:"Jun 22, 2023",runtime:"30m"},{name:"Sundae",air:"Jun 22, 2023",runtime:"30m"},{name:"Honeydew",air:"Jun 22, 2023",runtime:"30m"},{name:"Pop",air:"Jun 22, 2023",runtime:"30m"},{name:"Fishes",air:"Jun 22, 2023",runtime:"66m"},{name:"Forks",air:"Jun 22, 2023",runtime:"30m"},{name:"Bolognese",air:"Jun 22, 2023",runtime:"30m"},{name:"Omelette",air:"Jun 22, 2023",runtime:"30m"},{name:"The Bear",air:"Jun 22, 2023",runtime:"39m"}]]},
  {id:"shogun",title:"Shōgun",year:2024,network:"FX",genres:["Drama","Historical"],score:4.7,art:"linear-gradient(145deg,#d89e5c 0%,#9a6048 38%,#514650 72%,#1d2527)",description:"In 17th-century Japan, Lord Yoshii Toranaga fights for his life as his enemies on the Council of Regents unite against him. A mysterious European ship appears in a nearby fishing village.",seasons:[[{name:"Anjin",air:"Feb 27, 2024",runtime:"70m"},{name:"Servants of Two Masters",air:"Feb 27, 2024",runtime:"59m"},{name:"Tomorrow Is Tomorrow",air:"Mar 5, 2024",runtime:"57m"},{name:"The Eightfold Fence",air:"Mar 12, 2024",runtime:"55m"},{name:"Broken to the Fist",air:"Mar 19, 2024",runtime:"58m"},{name:"Ladies of the Willow World",air:"Mar 26, 2024",runtime:"54m"},{name:"A Stick of Time",air:"Apr 2, 2024",runtime:"57m"},{name:"The Abyss of Life",air:"Apr 9, 2024",runtime:"60m"},{name:"Crimson Sky",air:"Apr 16, 2024",runtime:"62m"},{name:"A Dream of a Dream",air:"Apr 23, 2024",runtime:"57m"}]]},
  {id:"the-last-of-us",title:"The Last of Us",year:2023,network:"HBO",genres:["Drama","Adventure"],score:4.2,art:"linear-gradient(145deg,#b5be83 0%,#788454 39%,#44523e 70%,#222923)",description:"Twenty years after modern civilization has been destroyed, Joel is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job becomes a brutal journey across the country.",seasons:[[{name:"When You're Lost in the Darkness",air:"Jan 15, 2023",runtime:"81m"},{name:"Infected",air:"Jan 22, 2023",runtime:"53m"},{name:"Long, Long Time",air:"Jan 29, 2023",runtime:"76m"},{name:"Please Hold to My Hand",air:"Feb 5, 2023",runtime:"50m"},{name:"Endure and Survive",air:"Feb 10, 2023",runtime:"59m"},{name:"Kin",air:"Feb 19, 2023",runtime:"59m"},{name:"Left Behind",air:"Feb 26, 2023",runtime:"56m"},{name:"When We Are in Need",air:"Mar 5, 2023",runtime:"51m"},{name:"Look for the Light",air:"Mar 12, 2023",runtime:"43m"}]]},
  {id:"abbott-elementary",title:"Abbott Elementary",year:2021,network:"ABC",genres:["Comedy","Workplace"],score:4.1,art:"linear-gradient(145deg,#ead8a2 0%,#c7ae78 37%,#78815d 70%,#2b3931)",description:"A workplace comedy following a group of dedicated teachers — and a slightly tone-deaf principal — as they navigate the Philadelphia public school system. Despite the odds, they are determined to help their students succeed.",seasons:[[{name:"Pilot",air:"Dec 7, 2021",runtime:"22m"},{name:"Light Bulb",air:"Jan 4, 2022",runtime:"22m"},{name:"Wishlist",air:"Jan 11, 2022",runtime:"22m"},{name:"New Tech",air:"Jan 18, 2022",runtime:"22m"},{name:"Student Transfer",air:"Jan 25, 2022",runtime:"22m"},{name:"Gifted Program",air:"Feb 1, 2022",runtime:"22m"},{name:"Art Teacher",air:"Feb 8, 2022",runtime:"22m"},{name:"Work Family",air:"Feb 15, 2022",runtime:"22m"},{name:"Step Class",air:"Feb 22, 2022",runtime:"22m"},{name:"Open House",air:"Mar 22, 2022",runtime:"22m"}]]},
  {id:"yellowjackets",title:"Yellowjackets",year:2021,network:"Showtime",genres:["Drama","Thriller"],score:4.0,art:"linear-gradient(145deg,#9ba758 0%,#66713a 38%,#57432f 70%,#24261d)",description:"A wildly talented high school girls' soccer team becomes the unlucky survivors of a plane crash deep in the Ontario wilderness. The series chronicles their descent from a complicated team to savage clans.",seasons:[[{name:"Pilot",air:"Nov 14, 2021",runtime:"59m"},{name:"F Sharp",air:"Nov 21, 2021",runtime:"55m"},{name:"The Dollhouse",air:"Nov 28, 2021",runtime:"55m"},{name:"Bear Down",air:"Dec 5, 2021",runtime:"55m"},{name:"Blood Hive",air:"Dec 12, 2021",runtime:"56m"}]]},
  {id:"only-murders",title:"Only Murders in the Building",year:2021,network:"Hulu",genres:["Comedy","Mystery"],score:4.0,art:"linear-gradient(145deg,#dfc57d 0%,#8e9a67 36%,#516148 70%,#252d27)",description:"Three strangers who share an obsession with true crime suddenly find themselves wrapped up in a real murder. They record a podcast to document their investigation and uncover the secrets of their building.",seasons:[[{name:"True Crime",air:"Aug 31, 2021",runtime:"33m"},{name:"Who Is Tim Kono?",air:"Aug 31, 2021",runtime:"32m"},{name:"How Well Do You Know Your Neighbors?",air:"Aug 31, 2021",runtime:"35m"},{name:"The Sting",air:"Aug 31, 2021",runtime:"33m"},{name:"Twist",air:"Aug 31, 2021",runtime:"34m"}]]}
];

const communityReviews=[
  {id:"community-1",user:"callahan",name:"Claire",color:"#21473f",time:"12m ago",showId:"severance",target:"S2 E7 · Chikhai Bardo",rating:5,text:"That was one of the most unnerving episodes of television I've seen in years. The sound design alone deserves its own award.",likes:38},
  {id:"community-2",user:"framebyframe",name:"Jules",color:"#413554",time:"38m ago",showId:"the-bear",target:"S2 E7 · Forks",rating:5,text:"Carmy thinks excellence has to hurt. Richie finds out it can feel like grace instead. I think about this episode every time I have a bad day.",likes:24},
  {id:"community-3",user:"cinephile94",name:"Morgan",color:"#57412c",time:"1h ago",showId:"succession",target:"S4 E3 · Connor's Wedding",rating:5,text:"The episode that made everyone in my group chat stop texting and just watch. Still hits like a dropped elevator.",likes:19},
  {id:"community-4",user:"sofasurfer",name:"Rae",color:"#3b5045",time:"3h ago",showId:"shogun",target:"Series review",rating:5,text:"Every frame looks like it was painted. The finale understood that power can be quiet, and that restraint can be devastating.",likes:16}
];
const listsSeed=[
  {id:"list-comfort",name:"Comfort shows for a hard week",description:"A few familiar worlds to disappear into.",owner:"Jules",showIds:["abbott-elementary","the-bear","only-murders","severance"]},
  {id:"list-one-season",name:"One season, no wasted episodes",description:"Short runs that know exactly where they're going.",owner:"Morgan",showIds:["shogun","the-last-of-us","yellowjackets"]},
  {id:"list-sunday",name:"Sunday night appointment television",description:"For the last hour before Monday.",owner:"Claire",showIds:["succession","severance","the-bear"]}
];
const STORE="serializd-clone-v1";
const fresh=()=>({logs:{},statuses:{},watchlist:[],likes:{},lists:[],followed:[]});
let data;try{data={...fresh(),...JSON.parse(localStorage.getItem(STORE)||"{}")}catch{data=fresh();}
const state={page:"home",showId:null,showTab:"Home",season:0,feed:"For you",searchQuery:"",listId:null};
let listShowTarget=null;
const $=(q,root=document)=>root.querySelector(q),$$=(q,root=document)=>[...root.querySelectorAll(q)];
const main=$("#main-content"),rail=$("#right-rail");
const ratingNames=["","Terrible","Bad","Okay","Good","Amazing"];
const escapeHtml=(s="")=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function save(){localStorage.setItem(STORE,JSON.stringify(data));}
function getShow(id){return shows.find(s=>s.id===id)}
function logKey(showId,season,episode){return `${showId}:${season}-${episode}`}
function episodeLog(showId,season,episode){return data.logs[logKey(showId,season,episode)]}
function showLogs(showId){return Object.values(data.logs).filter(l=>l.showId===showId)}
function allLogs(){return Object.values(data.logs).sort((a,b)=>b.watchedOn.localeCompare(a.watchedOn)||b.savedAt-a.savedAt)}
function averageFor(showId){const logs=showLogs(showId);return logs.length?logs.reduce((sum,l)=>sum+l.rating,0)/logs.length:null}
function showRating(showId){return data.statuses[showId]?.rating||null}
function ratingStars(rating){if(!rating)return "";return `${"★".repeat(rating)}${"☆".repeat(5-rating)}`}
function poster(show,cls="poster"){return `<div class="${cls}" style="--art:${show.art}"><div class="poster-copy"><div class="poster-title">${escapeHtml(show.title)}</div></div></div>`}
function fullPoster(show){return `<div class="show-poster" style="--art:${show.art}"><div class="poster-copy"><div class="poster-title">${escapeHtml(show.title)}</div></div></div>`}
function go(page){state.page=page;state.showId=null;state.listId=null;location.hash=page;render()}
function openShow(id){state.page="show";state.showId=id;state.showTab="Home";state.season=0;location.hash=`show/${id}`;render();window.scrollTo({top:0,behavior:"smooth"})}
function syncNav(){const route=state.page==="show"?"discover":state.page;$$('.main-nav a').forEach(a=>a.classList.toggle("active",a.dataset.page===route));}
function render(){syncNav();if(state.page==="show"&&state.showId)renderShow();else if(state.page==="discover")renderDiscover();else if(state.page==="reviews")renderReviews();else if(state.page==="lists")renderLists();else if(state.page==="profile")renderProfile();else renderHome();renderRail()}
function showCard(show){const personal=showRating(show.id);return `<article class="show-card" role="button" tabindex="0" data-show="${show.id}">${poster(show)}${show.score?`<span class="poster-rating">★ ${show.score.toFixed(1)}</span>`:""}${!personal?`<span class="poster-tag">${show.network.toUpperCase()}</span>`:""}<p class="show-card-title">${escapeHtml(show.title)}</p><p class="show-card-sub">${personal?`YOUR RATING · ${personal} ★`:show.year+" · "+escapeHtml(show.genres[0])}</p></article>`}
function bindShows(root=main){$$('[data-show]',root).forEach(el=>{el.addEventListener("click",()=>openShow(el.dataset.show));el.addEventListener("keydown",e=>{if(e.key==="Enter")openShow(el.dataset.show)})})}
function reviewCard(review,compact=false){const show=getShow(review.showId);if(!show)return"";const liked=Boolean(data.likes[review.id]);return `<article class="feed-card"><div class="feed-author"><span class="user-avatar" style="--avatar-bg:${review.color||"#28453b"}">${escapeHtml(review.name.slice(0,1).toUpperCase())}</span><div class="author-copy"><strong>${escapeHtml(review.name)}</strong> <span>@${escapeHtml(review.user)} · ${escapeHtml(review.time)}</span></div><button class="action-link" data-profile="${escapeHtml(review.user)}">•••</button></div><div class="feed-review"><button class="feed-poster" data-show="${show.id}" style="--art:${show.art}" aria-label="Open ${escapeHtml(show.title)}"><b>${escapeHtml(show.title)}</b></button><div class="review-body"><div class="review-meta"><strong data-show="${show.id}" class="text-show">${escapeHtml(show.title)}</strong><br>${escapeHtml(review.target)}</div><div class="review-stars" aria-label="${review.rating} out of 5">${ratingStars(review.rating)}</div><p class="review-text">${escapeHtml(review.text)}</p><div class="review-actions"><button class="action-link ${liked?"liked":""}" data-like="${review.id}"><span class="heart">${liked?"♥":"♡"}</span> ${Number(review.likes)+(liked?1:0)}</button><button class="action-link" data-reply="${review.id}">↩ REPLY</button>${compact?`<button class="action-link" data-show="${show.id}">DISCUSS</button>`:""}</div></div></div></article>`}
function userReviews(){const episodes=allLogs().filter(log=>log.review).map(log=>{const s=getShow(log.showId),ep=s?.seasons[log.season]?.[log.episode];return s&&ep?{id:`mine-${log.showId}-${log.season}-${log.episode}`,user:"you",name:"You",color:"#214e43",time:log.watchedOn,showId:s.id,target:`S${log.season+1} E${log.episode+1} · ${ep.name}`,rating:log.rating,text:log.review,likes:0}:null}).filter(Boolean);const series=Object.entries(data.statuses).filter(([,status])=>status.review&&status.rating).map(([showId,status])=>({id:`mine-series-${showId}`,user:"you",name:"You",color:"#214e43",time:status.reviewDate||"Recently",showId,target:"Series review",rating:status.rating,text:status.review,likes:0}));return [...episodes,...series]}
function feedItems(){return [...userReviews(),...communityReviews]}
function renderHome(){let items=feedItems();if(state.feed==="Following")items=items.filter(item=>item.user==="you"||data.followed.includes(item.user));main.innerHTML=`<section class="page-heading"><p class="eyebrow">Your television community</p><h1>Home</h1><p>Catch up with the shows and people you follow.</p></section><div class="feed-tabs"><button class="${state.feed==="For you"?"active":""}" data-feed="For you">For you</button><button class="${state.feed==="Following"?"active":""}" data-feed="Following">Following</button></div>${items.length?`<div class="feed">${items.map(item=>reviewCard(item,true)).join("")}</div>`:`<div class="empty-state"><h2>${state.feed==="Following"?"Your following feed is quiet":"Your feed is ready"}</h2><p>${state.feed==="Following"?"Follow TV fans to see their reviews here.":"Follow people and log episodes to build your TV community."}</p><button class="button primary" data-go="discover">Discover shows</button></div>`}<section class="section-gap"><div class="heading-row"><h2>Popular right now</h2><button class="view-link" data-go="discover">VIEW ALL →</button></div><div class="show-shelf">${shows.slice(0,5).map(showCard).join("")}</div></section>`;$$('[data-feed]',main).forEach(b=>b.addEventListener("click",()=>{state.feed=b.dataset.feed;renderHome()}));bindShared(main)}
function renderDiscover(){const q=state.searchQuery.trim().toLowerCase();const catalog=shows.filter(s=>!q||`${s.title} ${s.network} ${s.genres.join(" ")}`.toLowerCase().includes(q));main.innerHTML=`<section class="page-heading"><p class="eyebrow">Find your next favorite</p><h1>Discover</h1><p>Trending, highly rated, and waiting for your watchlist.</p></section><div class="heading-row"><h2>${q?`Search results for “${escapeHtml(state.searchQuery)}”`:"Trending TV shows"}</h2><select class="review-sort" id="discover-sort"><option value="trending">Trending</option><option value="rating">Highest rated</option><option value="new">Recently added</option><option value="az">A–Z</option></select></div><div class="show-shelf discover-shelf">${catalog.map(showCard).join("")||`<p class="muted">No shows match that search.</p>`}</div><section class="section-gap"><div class="heading-row"><h2>Highest rated</h2><span class="muted">MEMBER RATINGS</span></div><div class="show-shelf">${[...catalog].sort((a,b)=>b.score-a.score).map(showCard).join("")}</div></section>`;$("#discover-sort").addEventListener("change",e=>{const sort=e.target.value;const sorted=[...catalog];if(sort==="rating")sorted.sort((a,b)=>b.score-a.score);if(sort==="az")sorted.sort((a,b)=>a.title.localeCompare(b.title));if(sort==="new")sorted.sort((a,b)=>b.year-a.year);$(".discover-shelf").innerHTML=sorted.map(showCard).join("");bindShows(main)});bindShows(main)}
function renderReviews(){const reviews=feedItems();main.innerHTML=`<section class="page-heading"><p class="eyebrow">Reviews from TV fans</p><h1>Reviews</h1><p>What people are saying about the latest episodes and series.</p></section><div class="review-toolbar"><h2>Latest reviews</h2><select class="review-sort" id="review-sort"><option>Latest</option><option>Most liked</option><option>Highest rated</option></select></div><div class="feed" id="reviews-feed">${reviews.map(r=>reviewCard(r)).join("")}</div>`;$("#review-sort").addEventListener("change",e=>{const sorted=[...reviews];if(e.target.value==="Most liked")sorted.sort((a,b)=>b.likes-a.likes);if(e.target.value==="Highest rated")sorted.sort((a,b)=>b.rating-a.rating);$("#reviews-feed").innerHTML=sorted.map(r=>reviewCard(r)).join("");bindShared(main)});bindShared(main)}
function renderLists(){const mine=data.lists;const all=[...mine,...listsSeed];main.innerHTML=`<section class="page-heading"><p class="eyebrow">Member-made collections</p><div class="heading-row"><h1>Lists</h1><button class="button primary" id="create-list">＋ Create a list</button></div><p>Find your next watch in a collection made by the community.</p></section><div class="content-tabs"><button class="active">Popular</button><button data-list-tab="Your lists">Your lists</button></div><div id="list-collection">${all.map(listCard).join("")}</div>`;$("#create-list").addEventListener("click",()=>$("#list-dialog").showModal());$$('[data-list-tab]',main).forEach(b=>b.addEventListener("click",()=>{$$('.content-tabs button',main).forEach(x=>x.classList.toggle("active",x===b));const showMine=b.dataset.listTab==="Your lists";$("#list-collection").innerHTML=(showMine?mine:all).map(listCard).join("")||`<div class="empty-state"><h3>No lists yet</h3><p>Start a collection of your favorite shows.</p></div>`;bindListCards()}));bindListCards()}
function listCard(list){const posters=list.showIds.slice(0,5).map(id=>getShow(id)).filter(Boolean);return `<article class="list-card" data-list="${list.id}"><div class="list-posters">${posters.map(s=>`<div class="trend-poster" style="--art:${s.art}"></div>`).join("")}</div><h3>${escapeHtml(list.name)}</h3><p>${escapeHtml(list.description)}</p><small>${posters.length} SHOWS · BY ${escapeHtml(list.owner.toUpperCase())}</small></article>`}
function bindListCards(){$$('[data-list]',main).forEach(card=>card.addEventListener("click",()=>openList(card.dataset.list)))}
function openList(id){const list=[...data.lists,...listsSeed].find(l=>l.id===id);if(!list)return;state.listId=id;state.page="list";renderList(list)}
function renderList(list){main.innerHTML=`<button class="view-link" data-go="lists">← BACK TO LISTS</button><div class="heading-row section-gap"><div><p class="eyebrow">A list by ${escapeHtml(list.owner)}</p><h1>${escapeHtml(list.name)}</h1></div></div><p class="muted">${escapeHtml(list.description)}</p><div class="show-shelf section-gap">${list.showIds.map(getShow).filter(Boolean).map(showCard).join("")}</div>`;bindShared(main)}
function renderProfile(){const logs=allLogs();const watched=Object.values(data.statuses).filter(s=>s.state==="Watched").length;main.innerHTML=`<section class="profile-header"><div class="profile-avatar">A</div><div class="profile-copy"><p class="eyebrow">TV enthusiast</p><h1>Alex</h1><p>@you · Member since today</p></div><div class="profile-stats"><div><strong>${logs.length}</strong><span>EPISODES</span></div><div><strong>${watched}</strong><span>SHOWS</span></div><div><strong>${data.followed.length}</strong><span>FOLLOWING</span></div></div><button class="button secondary" id="edit-profile">Edit profile</button></section><div class="content-tabs"><button class="active">Diary</button><button data-profile-tab="Shows">Shows</button><button data-profile-tab="Stats">Stats</button></div><div id="profile-content">${renderDiaryMarkup(logs)}</div>`;$$('[data-profile-tab]',main).forEach(b=>b.addEventListener("click",()=>{ $$('.content-tabs button',main).forEach(x=>x.classList.toggle("active",x===b));const pane=$("#profile-content");if(b.dataset.profileTab==="Shows")pane.innerHTML=`<div class="show-shelf">${Object.keys(data.statuses).map(getShow).filter(Boolean).map(showCard).join("")||`<p class="muted">Your tracked shows will appear here.</p>`}</div>`;else pane.innerHTML=`<div class="stats-row"><div class="stat-box"><strong>${logs.length}</strong><span>EPISODES LOGGED</span></div><div class="stat-box"><strong>${Object.keys(data.statuses).length}</strong><span>SHOWS TRACKED</span></div><div class="stat-box"><strong>${Math.round(logs.reduce((n,l)=>n+(getShow(l.showId)?.seasons[l.season][l.episode].runtimeMinutes||42),0)/60)}h</strong><span>TIME WATCHED</span></div><div class="stat-box"><strong>${logs.length?(logs.reduce((n,l)=>n+l.rating,0)/logs.length).toFixed(1):"—"}</strong><span>AVERAGE RATING</span></div></div>`;bindShows(pane)}));bindShared(main)}
function renderDiaryMarkup(logs){if(!logs.length)return `<div class="empty-state"><h3>Your TV diary starts here.</h3><p>Log an episode to remember what you watched and what you thought.</p><button class="button primary" data-go="discover">Find a show</button></div>`;return `<div class="feed">${logs.map(log=>{const s=getShow(log.showId),e=s.seasons[log.season][log.episode];const r={id:"diary"+log.savedAt,user:"you",name:"You",color:"#214e43",time:log.watchedOn,showId:s.id,target:`S${log.season+1} E${log.episode+1} · ${e.name}`,rating:log.rating,text:log.review||"Watched an episode.",likes:0};return reviewCard(r)}).join("")}</div>`}
function renderShow(){const s=getShow(state.showId);if(!s){state.page="discover";return renderDiscover()}const tracked=data.statuses[s.id]?.state||"";const userRating=showRating(s.id);const total=s.seasons.reduce((n,season)=>n+season.length,0);const watched=showLogs(s.id).length;const tabs=["Home","Reviews","Lists","Media","Cast/Crew","Similar"];
  main.innerHTML=`<section class="show-hero" style="--backdrop:${s.art}"><div class="show-head">${fullPoster(s)}<div class="show-info"><div class="show-facts">${s.year} · ${s.seasons.length} season${s.seasons.length===1?"":"s"} · ${s.genres.map(escapeHtml).join(", ")}</div><h1>${escapeHtml(s.title)}</h1><div class="show-facts">${escapeHtml(s.network)} · ${total} episodes</div><p class="show-description">${escapeHtml(s.description)}</p><div class="show-ratingline">★ ${s.score.toFixed(2)} <small>COMMUNITY RATING</small>${userRating?`<span>·</span> ${userRating} ★ <small>YOUR RATING</small>`:""}</div><div class="show-buttons"><button class="button primary" id="track-show">${tracked?escapeHtml(tracked):"＋ Track show"}</button><button class="button secondary" id="rate-show">${userRating?`Your rating · ${userRating} ★`:"☆ Rate show"}</button><button class="button secondary" id="watchlist-show">${data.watchlist.includes(s.id)?"✓ Watchlisted":"＋ Watchlist"}</button></div></div></div></section><div class="show-tabs">${tabs.map(tab=>`<button class="${state.showTab===tab?"active":""}" data-show-tab="${tab}">${tab}</button>`).join("")}</div><div id="show-tab-content">${showTabMarkup(s)}</div>`;
  $$('[data-show-tab]',main).forEach(b=>b.addEventListener("click",()=>{state.showTab=b.dataset.showTab;renderShow()}));$("#track-show").addEventListener("click",()=>cycleStatus(s));$("#watchlist-show").addEventListener("click",()=>{data.watchlist=data.watchlist.includes(s.id)?data.watchlist.filter(id=>id!==s.id):[...data.watchlist,s.id];save();renderShow();toast(data.watchlist.includes(s.id)?"Added to watchlist":"Removed from watchlist")});$("#rate-show").addEventListener("click",()=>openLog(s.id,0,0,"show"));bindShared(main);}
function showTabMarkup(s){if(state.showTab==="Home")return `<div class="heading-row"><h2>Seasons</h2><span class="muted">${watchedCount(s.id)} OF ${s.seasons.reduce((n,x)=>n+x.length,0)} EPISODES WATCHED</span></div>${s.seasons.map((season,si)=>`<section class="season-card"><header class="season-head" data-toggle-season="${si}"><h3>Season ${si+1}</h3><span>${season.length} episodes ${si===state.season?"⌃":"⌄"}</span></header>${si===state.season?season.map((ep,ei)=>episodeRow(s,si,ei,ep)).join(""):""}</section>`).join("")}`;
  if(state.showTab==="Reviews"){const reviews=communityReviews.filter(r=>r.showId===s.id);return `<div class="heading-row"><h2>Reviews</h2><button class="button primary" id="review-this-show">Write a review</button></div>${reviews.length?`<div class="feed">${reviews.map(r=>reviewCard(r)).join("")}</div>`:`<div class="empty-state"><h3>No reviews for ${escapeHtml(s.title)} yet.</h3><p>Log an episode or rate the series to start the conversation.</p><button class="button primary" id="review-empty">Write the first review</button></div>`}`}
  if(state.showTab==="Lists")return `<div class="heading-row"><h2>Lists featuring ${escapeHtml(s.title)}</h2><button class="button primary" id="add-to-list">＋ Create a list with this show</button></div>${[...data.lists,...listsSeed].filter(l=>l.showIds.includes(s.id)).map(listCard).join("")||`<div class="empty-state"><h3>No lists yet</h3><p>This show hasn't been added to a list.</p></div>`}`;
  if(state.showTab==="Similar")return `<div class="heading-row"><h2>More shows like ${escapeHtml(s.title)}</h2></div><div class="show-shelf">${shows.filter(x=>x.id!==s.id&&x.genres.some(g=>s.genres.includes(g))).map(showCard).join("")}</div>`;
  if(state.showTab==="Media")return `<div class="empty-state"><h3>Media gallery</h3><p>Trailers, clips, and stills for ${escapeHtml(s.title)} will appear here.</p></div>`;
  return `<div class="empty-state"><h3>Cast and crew</h3><p>Cast and crew details for ${escapeHtml(s.title)} will appear here.</p></div>`;
}
function watchedCount(id){return showLogs(id).length}
function episodeRow(s,si,ei,ep){const log=episodeLog(s.id,si,ei);return `<article class="episode-row"><span class="ep-number">${String(ei+1).padStart(2,"0")}</span><div class="ep-details"><h4 class="ep-title">${escapeHtml(ep.name)}</h4><div class="ep-meta">${escapeHtml(ep.air)} · ${escapeHtml(ep.runtime)}</div></div><div class="ep-actions">${log?`<span class="ep-stars">${ratingStars(log.rating)}</span>`:""}<button class="ep-button" data-log="${s.id}|${si}|${ei}">${log?"EDIT LOG":"＋ LOG"}</button></div></article>`}
function cycleStatus(s){const cycle=["Watching","Watched","Paused","Dropped"];const old=data.statuses[s.id]?.state;const index=cycle.indexOf(old);const next=cycle[(index+1)%cycle.length];data.statuses[s.id]={...(data.statuses[s.id]||{}),state:next};if(next==="Watched")data.statuses[s.id].finishedOn=new Date().toISOString().slice(0,10);save();renderShow();toast(`${s.title}: ${next.toLowerCase()}`)}
function renderRail(){const popular=[...shows].sort((a,b)=>b.score-a.score).slice(0,5);rail.innerHTML=`<section class="rail-card"><header class="rail-heading"><h2>Trending TV</h2><a href="#discover" data-go="discover">SEE ALL →</a></header><div class="rail-body">${popular.map((s,i)=>`<div class="trend-row" data-show="${s.id}"><span class="trend-num">${i+1}</span><span class="trend-poster" style="--art:${s.art}"></span><span class="trend-name"><strong>${escapeHtml(s.title)}</strong><small>★ ${s.score.toFixed(2)} · ${s.year}</small></span></div>`).join("")}</div></section><section class="rail-card"><header class="rail-heading"><h2>Popular reviews</h2><a href="#reviews" data-go="reviews">MORE →</a></header>${communityReviews.slice(0,3).map(r=>`<div class="rail-review"><p>“${escapeHtml(r.text.slice(0,85))}${r.text.length>85?"…":""}”</p><small>${escapeHtml(r.name)} · ${escapeHtml(getShow(r.showId).title)} · ${ratingStars(r.rating)}</small></div>`).join("")}</section><section class="rail-card"><header class="rail-heading"><h2>People to follow</h2><span>COMMUNITY</span></header><div class="rail-body popular-list">${[{n:"Claire",u:"callahan",c:"#21473f"},{n:"Jules",u:"framebyframe",c:"#413554"},{n:"Morgan",u:"cinephile94",c:"#57412c"}].map(p=>`<div class="popular-user"><span class="user-avatar" style="--avatar-bg:${p.c}">${p.n[0]}</span><span>${p.n} <small class="muted">@${p.u}</small></span><button class="action-link" data-follow="${p.u}">${data.followed.includes(p.u)?"FOLLOWING":"+ FOLLOW"}</button></div>`).join("")}</div></section><p class="rail-note">TV data and titles are included for this independent fan-made project. Your activity is saved in this browser.</p>`;bindShared(rail)}
function bindShared(root=document){$$('[data-show]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>openShow(el.dataset.show))});$$('[data-go]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>go(el.dataset.go))});$$('[data-like]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>{data.likes[el.dataset.like]=!data.likes[el.dataset.like];save();render()})});$$('[data-log]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>{const [id,season,episode]=el.dataset.log.split("|");openLog(id,Number(season),Number(episode))})});$$('[data-toggle-season]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>{state.season=Number(el.dataset.toggleSeason);renderShow()})});$$('[data-follow]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>{const user=el.dataset.follow;data.followed=data.followed.includes(user)?data.followed.filter(x=>x!==user):[...data.followed,user];save();render()})});$$('[data-reply]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>toast("Replies are coming soon"))});$$('[data-profile]',root).forEach(el=>{if(el.dataset.bound)return;el.dataset.bound="1";el.addEventListener("click",()=>go("profile"))})}
let draftRating=null;
function openLog(showId,season,episode,kind="episode"){const s=getShow(showId);const prior=episodeLog(showId,season,episode);const ep=s.seasons[season]?.[episode];$("#log-title").textContent=kind==="show"?`Rate ${s.title}`:prior?"Edit episode log":"Log an episode";$("#log-subtitle").textContent=kind==="show"?`${s.title} · series rating`:`${s.title} · Season ${season+1}, Episode ${episode+1} · ${ep.name}`;$("#log-key").value=kind==="show"?`${showId}:show`:`${showId}|${season}|${episode}`;$("#log-review").value=prior?.review||"";$("#log-date").value=prior?.watchedOn||new Date().toISOString().slice(0,10);$("#log-spoiler").checked=prior?.spoiler||false;draftRating=kind==="show"?showRating(showId):prior?.rating||null;drawStars();$("#log-dialog").showModal()}
function drawStars(hover=null){const host=$("#star-picker");host.innerHTML=Array.from({length:5},(_,i)=>`<button type="button" class="star ${(hover??draftRating??0)>=i+1?"selected":""}" data-star="${i+1}" role="radio" aria-checked="${draftRating===i+1}" aria-label="${i+1} stars">${(hover??draftRating??0)>=i+1?"★":"☆"}</button>`).join("");$$('[data-star]',host).forEach(b=>{b.addEventListener("mouseenter",()=>drawStars(Number(b.dataset.star)));b.addEventListener("mouseleave",()=>drawStars());b.addEventListener("focus",()=>drawStars(Number(b.dataset.star)));b.addEventListener("click",()=>{draftRating=Number(b.dataset.star);drawStars()})});$("#rating-hint").textContent=draftRating?`${draftRating} / 5 · ${ratingNames[draftRating]}`:"Tap a star to rate";$("#save-log").disabled=!draftRating}
$("#log-form").addEventListener("submit",e=>{e.preventDefault();if(!draftRating)return;const key=$("#log-key").value;const review=$("#log-review").value.trim(),watchedOn=$("#log-date").value,spoiler=$("#log-spoiler").checked;if(key.endsWith(":show")){const showId=key.slice(0,-5);data.statuses[showId]={...(data.statuses[showId]||{}),rating:draftRating,review,reviewDate:watchedOn};}else{const [showId,season,episode]=key.split("|");data.logs[logKey(showId,Number(season),Number(episode))]={showId,season:Number(season),episode:Number(episode),rating:draftRating,review,watchedOn,spoiler,savedAt:Date.now()};if(!data.statuses[showId])data.statuses[showId]={state:"Watching"};}save();$("#log-dialog").close();render();toast("Saved to your TV diary")});
$("#list-form").addEventListener("submit",e=>{e.preventDefault();const name=$("#list-name").value.trim();if(!name)return;const list={id:`mine-${Date.now()}`,name,description:$("#list-description").value.trim(),owner:"You",showIds:listShowTarget?[listShowTarget]:[]};data.lists.unshift(list);listShowTarget=null;save();$("#list-dialog").close();$("#list-form").reset();renderLists();toast("Your list is ready")});
function bindShowTabButtons(){if(state.showTab!=="Home")return;$$('[data-toggle-season]',main).forEach(el=>{el.addEventListener("click",()=>{state.season=Number(el.dataset.toggleSeason);renderShow()})});$$('[data-log]',main).forEach(el=>el.addEventListener("click",()=>{const [id,season,episode]=el.dataset.log.split("|");openLog(id,Number(season),Number(episode))}))}
$("#main-content").addEventListener("click",e=>{if(e.target.id==="review-this-show"||e.target.id==="review-empty")openLog(state.showId,0,0,"show");if(e.target.id==="add-to-list"){listShowTarget=state.showId;$("#list-dialog").showModal()}});
$$('[data-close-dialog]').forEach(button=>button.addEventListener("click",()=>button.closest("dialog").close()));
$$('.main-nav a').forEach(link=>link.addEventListener("click",e=>{e.preventDefault();go(link.dataset.page)}));
$("#profile-trigger").addEventListener("click",()=>go("profile"));
$("#search-trigger").addEventListener("click",()=>{$("#search-dialog").showModal();$("#search-input").focus()});
$("#search-input").addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();const found=shows.filter(s=>`${s.title} ${s.network} ${s.genres.join(" ")}`.toLowerCase().includes(q));$("#search-results").innerHTML=q?found.map(s=>`<button class="search-result" data-search-show="${s.id}">${poster(s,"trend-poster")}<span class="result-copy"><strong>${escapeHtml(s.title)}</strong><small>${s.year} · ${escapeHtml(s.genres.join(", "))}</small></span><span class="result-year">★ ${s.score.toFixed(1)}</span></button>`).join("")||`<p class="muted">No matching shows.</p>`:`<p class="muted">Search the show catalogue.</p>`;$$('[data-search-show]').forEach(b=>b.addEventListener("click",()=>{$("#search-dialog").close();openShow(b.dataset.searchShow)}))});
$(document).addEventListener("keydown",e=>{if(e.key==="/"&&!e.ctrlKey&&!e.metaKey&&!$("input:focus, textarea:focus")){e.preventDefault();$("#search-dialog").showModal();$("#search-input").focus()}if(e.key==="Escape")$$('dialog[open]').forEach(d=>d.close())});
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("visible");clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove("visible"),2200)}
window.addEventListener("hashchange",()=>{const parts=location.hash.slice(1).split("/");if(parts[0]==="show"&&parts[1]){state.page="show";state.showId=parts[1]}else if(["home","discover","reviews","lists","profile"].includes(parts[0])){state.page=parts[0];state.showId=null}render()});
const initial=location.hash.slice(1).split("/");if(initial[0]==="show"&&initial[1]){state.page="show";state.showId=initial[1]}else if(["discover","reviews","lists","profile"].includes(initial[0]))state.page=initial[0];
render();
