const shows = [
  { id:"severance", title:"Severance", network:"APPLE TV+", years:"2022–", genres:["Sci-fi","Mystery"], description:"Mark leads a team of office workers whose memories have been surgically divided between work and personal life. A colleague's arrival sets them on a search for the truth behind their jobs.", art:"linear-gradient(145deg,#a5c7bc 0%,#69827a 38%,#34423d 70%,#1c2522)", tag:"POPULAR", seasons:[[{name:"Good News About Hell",date:"Feb 18, 2022"},{name:"Half Loop",date:"Feb 18, 2022"},{name:"In Perpetuity",date:"Feb 25, 2022"},{name:"The You You Are",date:"Mar 4, 2022"},{name:"The Grim Barbarity of Optics and Design",date:"Mar 11, 2022"},{name:"Hide and Seek",date:"Mar 18, 2022"},{name:"Defiant Jazz",date:"Mar 25, 2022"},{name:"What's for Dinner?",date:"Apr 1, 2022"},{name:"The We We Are",date:"Apr 8, 2022"}],[{name:"Hello, Ms. Cobel",date:"Jan 17, 2025"},{name:"Goodbye, Mrs. Selvig",date:"Jan 24, 2025"},{name:"Who Is Alive?",date:"Jan 31, 2025"},{name:"Woe's Hollow",date:"Feb 7, 2025"},{name:"Trojan's Horse",date:"Feb 14, 2025"},{name:"Attila",date:"Feb 21, 2025"},{name:"Chikhai Bardo",date:"Feb 28, 2025"},{name:"Sweet Vitriol",date:"Mar 7, 2025"},{name:"The After Hours",date:"Mar 14, 2025"},{name:"Cold Harbor",date:"Mar 21, 2025"}]] },
  { id:"bear", title:"The Bear", network:"FX", years:"2022–", genres:["Comedy","Drama"], description:"A young chef returns home to Chicago to run his family's sandwich shop, where the kitchen is full of pressure, grief, and people trying to make something better together.", art:"linear-gradient(145deg,#d59754 0%,#9a5339 42%,#583228 73%,#261e19)", tag:"", seasons:[[{name:"System",date:"Jun 23, 2022"},{name:"Hands",date:"Jun 23, 2022"},{name:"Brigade",date:"Jun 23, 2022"},{name:"Dogs",date:"Jun 23, 2022"},{name:"Sheridan",date:"Jun 23, 2022"},{name:"Ceres",date:"Jun 23, 2022"},{name:"Review",date:"Jun 23, 2022"},{name:"Braciole",date:"Jun 23, 2022"}],[{name:"Beef",date:"Jun 22, 2023"},{name:"Pasta",date:"Jun 22, 2023"},{name:"Sundae",date:"Jun 22, 2023"},{name:"Honeydew",date:"Jun 22, 2023"},{name:"Pop",date:"Jun 22, 2023"},{name:"Fishes",date:"Jun 22, 2023"},{name:"Forks",date:"Jun 22, 2023"},{name:"Bolognese",date:"Jun 22, 2023"},{name:"Omelette",date:"Jun 22, 2023"},{name:"The Bear",date:"Jun 22, 2023"}],[{name:"Tomorrow",date:"Jun 26, 2024"},{name:"Next",date:"Jun 26, 2024"},{name:"Doors",date:"Jun 26, 2024"},{name:"Violet",date:"Jun 26, 2024"},{name:"Children",date:"Jun 26, 2024"},{name:"Napkins",date:"Jun 26, 2024"},{name:"Legacy",date:"Jun 26, 2024"},{name:"Ice Chips",date:"Jun 26, 2024"},{name:"Apologies",date:"Jun 26, 2024"},{name:"Forever",date:"Jun 26, 2024"}]] },
  { id:"abbott", title:"Abbott Elementary", network:"ABC", years:"2021–", genres:["Comedy","Workplace"], description:"In one of Philadelphia's least-funded public schools, a group of dedicated teachers and a slightly tone-deaf principal try to give their students the best education they can.", art:"linear-gradient(145deg,#efdda4 0%,#cbb374 42%,#78815a 72%,#303b31)", tag:"", seasons:[[{name:"Pilot",date:"Dec 7, 2021"},{name:"Light Bulb",date:"Jan 4, 2022"},{name:"Wishlist",date:"Jan 11, 2022"},{name:"New Tech",date:"Jan 18, 2022"},{name:"Student Transfer",date:"Jan 25, 2022"},{name:"Gifted Program",date:"Feb 1, 2022"},{name:"Art Teacher",date:"Feb 8, 2022"},{name:"Work Family",date:"Feb 15, 2022"},{name:"Step Class",date:"Feb 22, 2022"},{name:"Open House",date:"Mar 22, 2022"}],[{name:"Development Day",date:"Sep 21, 2022"},{name:"Wrong Delivery",date:"Sep 28, 2022"},{name:"Story Samurai",date:"Oct 5, 2022"},{name:"The Principal's Office",date:"Oct 12, 2022"},{name:"Juice",date:"Oct 19, 2022"}]] },
  { id:"shogun", title:"Shōgun", network:"FX", years:"2024", genres:["Drama","Historical"], description:"In 17th-century Japan, a shipwrecked English sailor becomes entangled in the political struggle of Lord Toranaga, a powerful daimyo fighting for survival.", art:"linear-gradient(145deg,#d39555 0%,#8e5140 40%,#454249 72%,#1d2228)", tag:"", seasons:[[{name:"Anjin",date:"Feb 27, 2024"},{name:"Servants of Two Masters",date:"Feb 27, 2024"},{name:"Tomorrow Is Tomorrow",date:"Mar 5, 2024"},{name:"The Eightfold Fence",date:"Mar 12, 2024"},{name:"Broken to the Fist",date:"Mar 19, 2024"},{name:"Ladies of the Willow World",date:"Mar 26, 2024"},{name:"A Stick of Time",date:"Apr 2, 2024"},{name:"The Abyss of Life",date:"Apr 9, 2024"},{name:"Crimson Sky",date:"Apr 16, 2024"},{name:"A Dream of a Dream",date:"Apr 23, 2024"}]] },
  { id:"last-of-us", title:"The Last of Us", network:"HBO", years:"2023–", genres:["Drama","Adventure"], description:"Twenty years after civilization collapses, a hardened survivor is hired to smuggle a teenager out of a quarantine zone. Their journey becomes a fight for a future neither expected.", art:"linear-gradient(145deg,#a9b47c 0%,#6c7a4b 40%,#3a4737 71%,#202720)", tag:"", seasons:[[{name:"When You're Lost in the Darkness",date:"Jan 15, 2023"},{name:"Infected",date:"Jan 22, 2023"},{name:"Long, Long Time",date:"Jan 29, 2023"},{name:"Please Hold to My Hand",date:"Feb 5, 2023"},{name:"Endure and Survive",date:"Feb 10, 2023"},{name:"Kin",date:"Feb 19, 2023"},{name:"Left Behind",date:"Feb 26, 2023"},{name:"When We Are in Need",date:"Mar 5, 2023"},{name:"Look for the Light",date:"Mar 12, 2023"}]] },
  { id:"only-murders", title:"Only Murders in the Building", network:"HULU", years:"2021–", genres:["Comedy","Mystery"], description:"Three strangers who share an obsession with true crime suddenly find themselves wrapped up in a real murder investigation in their apartment building.", art:"linear-gradient(145deg,#d7bc79 0%,#819061 37%,#435640 71%,#222c27)", tag:"", seasons:[[{name:"True Crime",date:"Aug 31, 2021"},{name:"Who Is Tim Kono?",date:"Aug 31, 2021"},{name:"How Well Do You Know Your Neighbors?",date:"Aug 31, 2021"},{name:"The Sting",date:"Aug 31, 2021"},{name:"Twist",date:"Aug 31, 2021"}]] },
  { id:"yellowjackets", title:"Yellowjackets", network:"SHOWTIME", years:"2021–", genres:["Drama","Thriller"], description:"A talented high school girls' soccer team survives a plane crash deep in the wilderness. Years later, the survivors are still carrying the secrets of what happened.", art:"linear-gradient(145deg,#899248 0%,#555e31 39%,#4b3b2a 70%,#20231d)", tag:"", seasons:[[{name:"Pilot",date:"Nov 14, 2021"},{name:"F Sharp",date:"Nov 21, 2021"},{name:"The Dollhouse",date:"Nov 28, 2021"},{name:"Bear Down",date:"Dec 5, 2021"},{name:"Blood Hive",date:"Dec 12, 2021"}]] },
  { id:"studio", title:"The Studio", network:"APPLE TV+", years:"2025–", genres:["Comedy","Satire"], description:"A newly appointed studio head and his team chase movie magic while trying to survive Hollywood's demands for money, compromise, and the next big hit.", art:"linear-gradient(145deg,#f2d34e 0%,#df874a 39%,#a8493d 70%,#422a2e)", tag:"NEW", seasons:[[{name:"The Promotion",date:"Mar 26, 2025"},{name:"The Oner",date:"Mar 26, 2025"},{name:"The Note",date:"Apr 2, 2025"},{name:"The Missing Reel",date:"Apr 9, 2025"},{name:"The War",date:"Apr 16, 2025"}]] }
];

const state = { page:"discover", filter:"all", sort:"popular", selectedShow:null, season:0, query:"", rating:null, draftRating:null };
const STORAGE_KEY = "episode-club-v1";
const emptyData = () => ({ logs:{}, watchlist:[], queue:{} });
let data;
try { data = {...emptyData(), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}")} } catch { data = emptyData(); }
const $ = (selector, root=document) => root.querySelector(selector);
const $$ = (selector, root=document) => [...root.querySelectorAll(selector)];
const main = $("#main-content");
const dialog = $("#log-dialog");
const ratingLabels = ["", "Didn't like it", "It was okay", "Liked it", "Really liked it", "Loved it"];
function persist(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
function escapeHtml(value=""){ return String(value).replace(/[&<>"']/g, ch => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[ch])); }
function showById(id){ return shows.find(show=>show.id===id); }
function allLogs(){ return Object.values(data.logs).sort((a,b)=>b.watchedOn.localeCompare(a.watchedOn)||b.updatedAt-a.updatedAt); }
function showLogs(id){ return allLogs().filter(log=>log.showId===id); }
function logFor(showId,episodeId){ return data.logs[`${showId}:${episodeId}`]; }
function showAverage(showId){ const logs=showLogs(showId); return logs.length ? logs.reduce((sum,log)=>sum+log.rating,0)/logs.length : null; }
function fmtRating(rating){ return rating==null ? "" : `${rating} ★`; }
function fmtDate(date){ if(!date)return "";return new Date(`${date}T12:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}); }
function posterMarkup(show, extra=""){ return `<div class="${extra||"poster"}" style="--art:${show.art}"><div class="poster-copy"><div class="poster-kicker">${escapeHtml(show.network)} · ${escapeHtml(show.years)}</div><div class="poster-title">${escapeHtml(show.title)}</div></div></div>`; }
function navTo(page){ state.page=page;state.selectedShow=null;location.hash=page;render(); }
function setNav(){ $$(".main-nav a").forEach(link=>link.classList.toggle("active",link.dataset.page===state.page)); }
function updateSummary(){ const logs=allLogs();const currentYear=String(new Date().getFullYear());const thisYear=logs.filter(log=>log.watchedOn.startsWith(currentYear));$("#year-summary").innerHTML=`<div class="summary-item"><strong>${thisYear.length}</strong>EPISODES THIS YEAR</div><div class="summary-item"><strong>${new Set(thisYear.map(log=>log.showId)).size}</strong>SHOWS LOGGED</div><div class="summary-item"><strong>${data.watchlist.length}</strong>ON YOUR LIST</div>`; }
function render(){ setNav();updateSummary();renderSidebar(); if(state.selectedShow){renderDetail();return;} if(state.page==="journal"){renderJournal();return;} if(state.page==="watchlist"){renderWatchlist();return;}renderDiscover(); }
function renderSidebar(){
  const queued=Object.entries(data.queue).map(([id,episodeId])=>({show:showById(id),episodeId})).filter(item=>item.show);
  $("#queue-content").innerHTML=queued.length?queued.map(({show,episodeId})=>{const [season,episode]=episodeId.split("-").map(Number);const max=show.seasons[season]?.length||1;return `<div class="queue-item"><div class="queue-title"><button data-open-show="${show.id}">${escapeHtml(show.title)}</button><span>S${season+1} · E${episode+1} / ${max}</span></div><div class="progress"><i style="width:${Math.max(6,episode/max*100)}%"></i></div></div>`}).join(""):`<p class="queue-empty">Your queue is empty. Open a show and choose <button data-queue-prompt>Start watching</button> to keep your place here.</p>`;
  const recent=allLogs().slice(0,4);
  $("#recent-content").innerHTML=recent.length?recent.map(log=>{const show=showById(log.showId);const episode=show?.seasons[log.season]?.[log.episode];return show&&episode?`<div class="recent-item"><div class="mini-poster" style="--art:${show.art}"></div><div class="recent-copy"><p><b>${escapeHtml(show.title)}</b> · S${log.season+1} E${log.episode+1}</p><small>${escapeHtml(episode.name)} &nbsp; <span class="recent-stars">${"★".repeat(log.rating)}${"☆".repeat(5-log.rating)}</span></small></div></div>`:""}).join(""):`<p class="queue-empty">Your episode diary will show up here.</p>`;
  $$("[data-open-show]").forEach(button=>button.addEventListener("click",()=>openShow(button.dataset.openShow)));
  $("[data-queue-prompt]")?.addEventListener("click",()=>navTo("discover"));
}
function renderDiscover(){
  const filtered=shows.filter(show=>{const matchesFilter=state.filter==="all"||(state.filter==="popular"&&["severance","bear","shogun","studio"].includes(show.id))||(state.filter==="new"&&show.tag==="NEW")||(state.filter==="watching"&&Boolean(data.queue[show.id]));const matchesQuery=!state.query||`${show.title} ${show.genres.join(" ")} ${show.network}`.toLowerCase().includes(state.query.toLowerCase());return matchesFilter&&matchesQuery;});
  if(state.sort==="alpha")filtered.sort((a,b)=>a.title.localeCompare(b.title));
  main.innerHTML=`<div class="section-heading"><h2>Find your next show</h2><button class="heading-action" id="sort-button">SORT: ${state.sort==="popular"?"POPULAR":"A–Z"} ↓</button></div><div class="filter-row">${[["all","All shows"],["popular","Popular"],["new","New"],["watching","Watching"]].map(([value,label])=>`<button class="filter-chip ${state.filter===value?"active":""}" data-filter="${value}">${label}</button>`).join("")}</div><div class="show-grid">${filtered.map(showCard).join("")||`<div class="empty-panel"><h3>No shows found</h3><p>Try another title, network, or genre.</p></div>`}</div>`;
  $$("[data-filter]",main).forEach(button=>button.addEventListener("click",()=>{state.filter=button.dataset.filter;renderDiscover();}));
  $("#sort-button",main).addEventListener("click",()=>{state.sort=state.sort==="popular"?"alpha":"popular";renderDiscover();});
  $$("[data-show-id]",main).forEach(card=>card.addEventListener("click",()=>openShow(card.dataset.showId)));
}
function showCard(show){const average=showAverage(show.id);const total=show.seasons.reduce((sum,season)=>sum+season.length,0);const logged=showLogs(show.id).length;return `<article class="show-card" tabindex="0" role="button" data-show-id="${show.id}" aria-label="Open ${escapeHtml(show.title)}">${posterMarkup(show)}${show.tag?`<span class="poster-tag">${show.tag}</span>`:""}<div class="poster-overlay"><span>${logged?`${logged} EPISODE${logged===1?"":"S"} LOGGED`:"OPEN SHOW"}</span></div><div class="card-meta"><span class="genres">${escapeHtml(show.genres.join(" · "))} · ${total} EPS</span><span class="card-rating">${average?`★ ${average.toFixed(1)}`:""}</span></div></article>`;}
function openShow(id){state.selectedShow=id;state.season=0;state.page="discover";render();window.scrollTo({top:0,behavior:"smooth"});}
function renderDetail(){const show=showById(state.selectedShow);if(!show){state.selectedShow=null;renderDiscover();return;}const seasons=show.seasons;const logs=showLogs(show.id);const average=showAverage(show.id);const queued=Object.hasOwn(data.queue,show.id);const currentEpisode=queued?data.queue[show.id]:null;
  main.innerHTML=`<div class="show-detail"><button class="back-link" id="back-to-discover">← BACK TO DISCOVER</button><div class="detail-top"><div class="detail-poster" style="--art:${show.art}"><div class="poster-copy"><div class="poster-kicker">${escapeHtml(show.network)}</div><div class="poster-title">${escapeHtml(show.title)}</div></div></div><div class="detail-info"><div class="detail-sub">${escapeHtml(show.network)} · ${escapeHtml(show.years)} · ${escapeHtml(show.genres.join(" / "))}</div><h2>${escapeHtml(show.title)}</h2><div class="detail-rating">${average?`★ ${average.toFixed(1)} YOUR EPISODE AVERAGE`:`NO EPISODES RATED YET`}</div><p class="detail-description">${escapeHtml(show.description)}</p><div class="detail-sub">${seasons.length} SEASON${seasons.length===1?"":"S"} · ${seasons.reduce((sum,season)=>sum+season.length,0)} EPISODES</div><div class="detail-actions"><button class="button button-primary" id="start-watching">${queued?"Log next episode":"Start watching"}</button><button class="button" id="toggle-watchlist">${data.watchlist.includes(show.id)?"✓ On watchlist":"＋ Watchlist"}</button></div></div></div><div class="section-heading"><h2>Episodes</h2><span class="season-summary">${logs.length} OF ${seasons.reduce((sum,season)=>sum+season.length,0)} LOGGED</span></div><div class="season-tabs">${seasons.map((season,index)=>`<button class="season-tab ${state.season===index?"active":""}" data-season="${index}">SEASON ${index+1}</button>`).join("")}</div><div class="episode-list">${seasons[state.season].map((episode,index)=>episodeRow(show,index,episode)).join("")}</div></div>`;
  $("#back-to-discover",main).addEventListener("click",()=>{state.selectedShow=null;renderDiscover();});
  $$("[data-season]",main).forEach(button=>button.addEventListener("click",()=>{state.season=Number(button.dataset.season);renderDetail();}));
  $$("[data-log-episode]",main).forEach(button=>button.addEventListener("click",()=>openLog(show.id,...button.dataset.logEpisode.split("-").map(Number))));
  $("#toggle-watchlist",main).addEventListener("click",()=>{const index=data.watchlist.indexOf(show.id);if(index<0){data.watchlist.push(show.id);toast("Added to your watchlist");}else{data.watchlist.splice(index,1);toast("Removed from your watchlist");}persist();renderDetail();});
  $("#start-watching",main).addEventListener("click",()=>{const next=currentEpisode||findNextEpisode(show);if(!next){toast("You’ve logged every episode");return;}data.queue[show.id]=`${next.season}-${next.episode}`;persist();openLog(show.id,next.season,next.episode);});
}
function episodeRow(show,index,episode){const key=`${state.season}-${index}`;const log=logFor(show.id,key);return `<article class="episode-row"><span class="episode-number">${String(index+1).padStart(2,"0")}</span><div class="episode-name"><h3>${escapeHtml(episode.name)}</h3><p>${escapeHtml(episode.date)}${log?.note?` · “${escapeHtml(log.note)}”`:""}</p></div>${log?`<button class="episode-rating" data-log-episode="${key}" aria-label="Edit your ${log.rating} star rating">${"★".repeat(log.rating)}${"☆".repeat(5-log.rating)}</button>`:`<button class="episode-log-button" data-log-episode="${key}">＋ RATE EPISODE</button>`}</article>`;}
function findNextEpisode(show){for(let season=0;season<show.seasons.length;season++){for(let episode=0;episode<show.seasons[season].length;episode++){if(!logFor(show.id,`${season}-${episode}`))return{season,episode};}}return null;}
function renderJournal(){const logs=allLogs();main.innerHTML=`<div class="section-heading"><h2>Your episode journal</h2><span class="season-summary">${logs.length} EPISODE${logs.length===1?"":"S"} LOGGED</span></div>${logs.length?`<div class="journal-list">${logs.map(journalEntry).join("")}</div>`:`<div class="empty-panel"><h3>Your diary starts here.</h3><p>Rate an episode and leave a note. Your viewing history will gather here as you go.</p><button class="button button-primary" id="journal-discover">Find a show</button></div>`}`;$("#journal-discover",main)?.addEventListener("click",()=>navTo("discover"));}
function journalEntry(log){const show=showById(log.showId);const episode=show?.seasons[log.season]?.[log.episode];if(!show||!episode)return"";return `<article class="journal-entry"><div class="journal-poster" style="--art:${show.art}"></div><div class="journal-body"><h3>${escapeHtml(show.title)}</h3><div class="episode-caption">S${log.season+1} E${log.episode+1} · ${escapeHtml(episode.name)} · <span class="card-rating">${"★".repeat(log.rating)}${"☆".repeat(5-log.rating)}</span></div>${log.note?`<p>${escapeHtml(log.note)}</p>`:""}</div><span class="journal-date">${fmtDate(log.watchedOn)}</span></article>`;}
function renderWatchlist(){const list=data.watchlist.map(showById).filter(Boolean);main.innerHTML=`<div class="section-heading"><h2>Your watchlist</h2><span class="season-summary">${list.length} SHOW${list.length===1?"":"S"}</span></div>${list.length?`<div class="show-grid">${list.map(showCard).join("")}</div>`:`<div class="empty-panel"><h3>Keep a show close for later.</h3><p>Add shows to your watchlist so you can find them when you’re ready to start something new.</p><button class="button button-primary" id="watchlist-discover">Browse shows</button></div>`}`;$("#watchlist-discover",main)?.addEventListener("click",()=>navTo("discover"));$$("[data-show-id]",main).forEach(card=>card.addEventListener("click",()=>openShow(card.dataset.showId)));}
function openLog(showId,season,episode){const show=showById(showId);const item=show.seasons[season][episode];const existing=logFor(showId,`${season}-${episode}`);$("#dialog-title").textContent=existing?"Edit your episode log":"Log an episode";$("#dialog-subtitle").textContent=`${show.title} · Season ${season+1}, Episode ${episode+1}: ${item.name}`;$("#log-show-id").value=showId;$("#log-episode-id").value=`${season}-${episode}`;$("#log-note").value=existing?.note||"";$("#log-date").value=existing?.watchedOn||new Date().toISOString().slice(0,10);state.draftRating=existing?.rating||null;renderStars();dialog.showModal();}
function renderStars(hovered=null){const holder=$("#star-picker");holder.innerHTML=Array.from({length:5},(_,index)=>{const rating=index+1;const on=(hovered??state.draftRating??0)>=rating;return `<button type="button" class="star ${on?"selected":""}" data-rating="${rating}" role="radio" aria-checked="${state.draftRating===rating}" aria-label="${rating} out of 5 stars">${on?"★":"☆"}</button>`}).join("");$$(".star",holder).forEach(button=>{button.addEventListener("mouseenter",()=>renderStars(Number(button.dataset.rating)));button.addEventListener("focus",()=>renderStars(Number(button.dataset.rating)));button.addEventListener("mouseleave",()=>renderStars());button.addEventListener("blur",()=>renderStars());button.addEventListener("click",()=>{state.draftRating=Number(button.dataset.rating);renderStars();});});$("#rating-hint").textContent=state.draftRating?`${state.draftRating} of 5 · ${ratingLabels[state.draftRating]}`:"Choose a rating";$("#save-log").disabled=!state.draftRating;}
$("#log-form").addEventListener("submit",event=>{if(event.submitter?.value==="cancel")return;event.preventDefault();if(!state.draftRating)return;const showId=$("#log-show-id").value;const [season,episode]=$("#log-episode-id").value.split("-").map(Number);const key=`${showId}:${season}-${episode}`;data.logs[key]={showId,season,episode,rating:state.draftRating,note:$("#log-note").value.trim(),watchedOn:$("#log-date").value,updatedAt:Date.now()};const next=findNextEpisode(showById(showId));if(next)data.queue[showId]=`${next.season}-${next.episode}`;else delete data.queue[showId];persist();dialog.close();render();toast("Episode saved to your journal");});
$("#search").addEventListener("input",event=>{state.query=event.target.value;if(!state.selectedShow&&state.page==="discover")renderDiscover();});
$$(".main-nav a").forEach(link=>link.addEventListener("click",event=>{event.preventDefault();navTo(link.dataset.page);}));
$("#profile-button").addEventListener("click",()=>navTo("journal"));
$("#log-dialog").addEventListener("click",event=>{if(event.target===dialog)dialog.close();});
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>el.classList.remove("show"),2200);}
window.addEventListener("hashchange",()=>{const page=location.hash.slice(1);if(["discover","journal","watchlist"].includes(page)){state.page=page;state.selectedShow=null;render();}});
const initialPage=location.hash.slice(1);if(["discover","journal","watchlist"].includes(initialPage))state.page=initialPage;
render();
